# Generated by Django 6.0.8 on 2026-09-11 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_exchangerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('color__regex', '^#[0-9A-Fa-f]{6}$')), name='account_color_valid_hex'),
        ),
    ]
