# Generated by Django 6.0.8 on 2026-09-09 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-10)])),
                ('valid_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_from', to='core.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_to', to='core.currency')),
            ],
            options={
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'valid_at'], name='exchange_rate_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'valid_at'), name='unique_exchange_rate_at_time')],
            },
        ),
    ]
