# Generated by Django 6.0.8 on 2026-09-09 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
    ]
