# Generated by Django 6.0.8 on 2026-09-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_currencies'),
        ('users', '0002_user_base_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.currency'),
            preserve_default=False,
        ),
    ]
